### ISSUE TITLE
高鉅金流外掛，付款方式設定問題

### ISSUE THREAD

**Issue by webbizben** [jyyan/woocommerce-mypay-payment#1]
您好：
我們在後台的 Payment Method 裡做設定，發現只要支付方式是選擇『全部』以外的選項（各別排除或是選取某個支付方式），都無法成功到達付款頁面。

如圖：
設定畫面：https://share.getcloudapp.com/jkuvv6W4
選擇除了『全部』以外的支付方式，遇到的錯誤畫面：https://share.getcloudapp.com/04uEEdWX

再請協助，謝謝

**Comment by jyyan** [comment]
收到，感謝您的回報

**Comment by jyyan** [comment]
已發佈更新版本 [v1.2.20220418](https://github.com/jyyan/woocommerce-mypay-payment/releases/tag/v1.2.20220418)
