### ISSUE TITLE
高鉅金流外掛，折價券使用問題

### ISSUE THREAD

**Issue by webbizben** [jyyan/woocommerce-mypay-payment#2]
您好：
當訪客購買商品時，填寫折價券代碼，選擇第四方金流支付，發現錯誤代碼100。
不知道要如何設定才能正常付款，再請協助，謝謝您

問題截圖：https://share.getcloudapp.com/mXuYQ5Ao

**Comment by jyyan** [comment]
您好

稍早有 pre-release [v1.2.20220504](https://github.com/jyyan/woocommerce-mypay-payment/releases/tag/v1.2.20220504) 這項 patch，請您再撥空測試

謝謝您

**Comment by webbizben** [comment]
您好：

我們有更新並測試，使用折價券已可以正常到達高鉅的支付頁面

謝謝您

**Comment by jyyan** [comment]
謝謝您協助測試 & 確認功能正常

thx
