### ISSUE TITLE
高鉅金流外掛，錯誤代碼 100 改善建議

### ISSUE THREAD

**Issue by webbizben** [jyyan/woocommerce-mypay-payment#3]
WooCommerce 結帳的總金額，除了包含商品金額、折價金額、運費，還會包含費用。

這個費用可以是管理員手動新增或編輯訂單時新增上去，如圖：[https://share.getcloudapp.com/p9uQvgkq](https://share.getcloudapp.com/p9uQvgkq)

也可以透過外掛自動加上，例如：[https://wordpress.org/plugins/woo-conditional-product-fees-for-checkout/](https://wordpress.org/plugins/woo-conditional-product-fees-for-checkout/)

或是透過程式自動加上，例如：[https://woocommerce.com/document/subscriptions/develop/recurring-cart-fees/](https://woocommerce.com/document/subscriptions/develop/recurring-cart-fees/)

常見的金流外掛，大多只會用到訂單總金額，所以有沒有費用，並沒有什麼影響。

但貴司的外掛在有費用的情況下，最後跳轉到 Mypay 會出現錯誤代碼 100，並出現錯誤訊息：「商品內容總金額+折價金額+運費 與 總金額不同。」

希望可以改善，謝謝。

**Comment by jyyan** [comment]
已於 [v1.2.20240115.2](https://github.com/jyyan/woocommerce-mypay-payment/releases/tag/v1.2.20240115.2) 修正

**Comment by jyyan** [comment]
![Screenshot from 2024-01-15 20-30-20](https://github.com/jyyan/woocommerce-mypay-payment/assets/1297451/81b0581e-2d43-4f89-afb9-b05f453b699d)
![Screenshot from 2024-01-15 20-44-50](https://github.com/jyyan/woocommerce-mypay-payment/assets/1297451/de4f34b8-ff99-41dd-8a7c-a9a0de5eb2df)
