### ISSUE TITLE
高鉅金流外掛(WooCommerce)錯誤代碼100，API串接錯誤(付款方式：虛擬帳號)

### ISSUE THREAD

**Issue by cuv2378** [jyyan/woocommerce-mypay-payment#4]
1. 確認提供2項付款方式：信用卡(1次付清)與虛擬帳號
2. 信用卡(付款)可以成功轉至MYPAY頁面，而虛擬帳號(付款)頁面顯示錯誤代碼100，API串接錯誤，如附件所示：

![API串接錯誤](https://github.com/jyyan/woocommerce-mypay-payment/assets/127809145/f425bc1c-9dff-4a9e-970f-a4da65ce3acf)

選擇MYMAY所有付款方式時，則可以成功轉至MYPAY頁面，頁面顯示有虛擬帳號的付款選項，如附件所示：
![MYPAY所有金流](https://github.com/jyyan/woocommerce-mypay-payment/assets/127809145/94c99a1c-faea-4e72-bb05-42d4ce31df93)

![所有付款方式顯示](https://github.com/jyyan/woocommerce-mypay-payment/assets/127809145/a4ea9c2f-5fbd-495a-9d3a-05615e6e9b45)
成功產生虛擬帳號
![產生虛擬帳號](https://github.com/jyyan/woocommerce-mypay-payment/assets/127809145/c5653c6b-9464-481e-b086-93b38d62cde3)

**Comment by jyyan** [comment]
感謝您回報此 ISSUE,
已排定處理

**Comment by jyyan** [comment]
已於 [v1.2.20240115.2](https://github.com/jyyan/woocommerce-mypay-payment/releases/tag/v1.2.20240115.2) 修正

![Screenshot from 2024-01-15 10-17-16](https://github.com/jyyan/woocommerce-mypay-payment/assets/1297451/b80a4467-12f2-4194-b0ea-5580ec127d4d)
