### ISSUE TITLE
Woocommerce 訂單狀態未更新

### ISSUE THREAD

**Issue by webbizben** [jyyan/woocommerce-mypay-payment#5]
使用 Woocommerce 8.5 與最新版的 Woocommerce-mypay-payment

測試下單後，會發生

1.高鉅後台顯示已付款完成
如圖：https://share.zight.com/p9uBNoQE

2.WP 網站後台的訂單狀態則顯示等待付款中
如圖：https://share.zight.com/o0uO7AXm

有另外再測試一次，Log 截圖如下
https://share.zight.com/P8uw8O2y

**Comment by jyyan** [comment]
請參考 [設定 Payment Gateway](https://github.com/jyyan/woocommerce-mypay-payment/blob/master/DOC/mypay-woocommerce-payment-gateway-install.md#%E8%A8%AD%E5%AE%9A-payment-gateway)
項目中：

1. 複製『Paymant Callback URL』欄位資料
2. 至 MyPay 金流後台：系統設定 > 金流服務系統 > 連線通知設定
3. 填寫於『即時交易回傳網址、非即時交易回傳網址』欄位，並點擊『測試』可測試 payment callback API 是否完成連線。

請協助提供您測試連線成功的截圖（會顯示提示訊息如下）
![Image](https://raw.githubusercontent.com/jyyan/woocommerce-mypay-payment/master/DOC/img/setup-5.png)

**Comment by webbizben** [comment]
您好：

謝謝回覆 

我有填寫 Paymant Callback URL ，並儲存，但顯示 
`連線成功，但資料回傳失敗(必須為8888)。回傳前20個字元為：<html> <head><title>401 Authorization Required</title></head> <body> <center><h1>401 Authorization Required</h1></center> <hr><center>nginx</center> </body> </html>`

如圖：https://share.zight.com/BluqbO1e

--

在這狀態下，我有在測試網站上下單，這次測試網站是有顯示正確的訂單狀態

**Comment by jyyan** [comment]
貴司網站顯示 **401 Authorization Required**
代表該 API 有其他原因，導致需要驗證權限，請貴司負責維護 PHP 程式、系統的同仁檢查：
1. 其他 wordpress 資安套件
2. WAF 防火牆規則
3. 主機 apache / nginx / IIS 的 URL / path 權限限制（鎖 ip 訪問、或鎖來源主機 host 訪問）

導致該 URL 被封鎖權限

**Comment by webbizben** [comment]
確實是安全防護的設定，導致 401 的狀態，目前測試正常

謝謝您的協助
